name: Docker Image CI

on:
  push:
    branches: [ version** ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      HAVE_DOCKERHUB_SECRET: ${{ secrets.DOCKERHUB_TOKEN != '' && secrets.DOCKERHUB_USERNAME != '' }}

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y cmake git libssl-dev libgmp-dev libtinfo5 libprotobuf-dev

      - name: Login to DockerHub
        uses: docker/login-action@v1
        id: login
        # If the user set up those variable, it's upstream or (s)he wants the push to happen
        # Otherwise, it might just be someone pushing to their fork, in which case we still
        # want to build as it's useful to test a release before upstreaming it.
        if: env.HAVE_DOCKERHUB_SECRET
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Build and push beacon-chain
        run: bazel run //cmd/beacon-chain:push_images --config=release
