name: Docker Image CI

on:
  push:
    branches: [ version** ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Install dependencies
        run: sudo apt install cmake git libssl-dev libgmp-dev libtinfo5 libprotoc-dev; sudo apt install apt-transport-https curl gnupg;
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg;
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings;
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list;sudo apt update && sudo apt install bazel

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v2
      - run: bazel build //cmd/beacon-chain:image_bundle --config=release
      -
        name: Build and push
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: srt180/beacon-chain:latest
